# Generated by Django 3.1.6 on 2021-02-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrangement',
            fields=[
                ('arrangementid', models.AutoField(db_column='ArrangementID', primary_key=True, serialize=False)),
                ('arrangementnavn', models.CharField(db_column='ArrangementNavn', max_length=256)),
                ('beskrivelse', models.TextField(blank=True, db_column='Beskrivelse', null=True)),
                ('antallplasser', models.IntegerField(blank=True, db_column='AntallPlasser', null=True)),
                ('lokasjon', models.CharField(blank=True, db_column='Lokasjon', max_length=128, null=True)),
                ('tidspunkt', models.DateTimeField(blank=True, db_column='Tidspunkt', null=True)),
                ('opprettet', models.DateTimeField(db_column='Opprettet')),
                ('pris', models.IntegerField(blank=True, db_column='Pris', null=True)),
                ('avlyst', models.IntegerField(db_column='Avlyst')),
            ],
            options={
                'db_table': 'arrangement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Arrangementinnhold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrangementid', models.IntegerField(db_column='ArrangementID')),
                ('innholdid', models.IntegerField(db_column='InnholdID')),
            ],
            options={
                'db_table': 'arrangementinnhold',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bruker',
            fields=[
                ('brukerid', models.AutoField(db_column='BrukerID', primary_key=True, serialize=False)),
                ('fornavn', models.CharField(db_column='Fornavn', max_length=128)),
                ('etternavn', models.CharField(db_column='Etternavn', max_length=128)),
                ('fodselsdato', models.DateTimeField(blank=True, db_column='Fodselsdato', null=True)),
                ('adresse', models.CharField(blank=True, db_column='Adresse', max_length=128, null=True)),
                ('postnummer', models.IntegerField(blank=True, db_column='Postnummer', null=True)),
                ('sted', models.CharField(blank=True, db_column='Sted', max_length=128, null=True)),
                ('eradministrator', models.IntegerField(db_column='ErAdministrator')),
                ('epost', models.CharField(db_column='Epost', max_length=128)),
                ('passord', models.CharField(db_column='Passord', max_length=256)),
                ('passordhash', models.CharField(db_column='PassordHash', max_length=256)),
            ],
            options={
                'db_table': 'bruker',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Harallergi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brukerid', models.IntegerField(db_column='BrukerID')),
                ('innholdid', models.IntegerField(db_column='InnholdID')),
            ],
            options={
                'db_table': 'harallergi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Innhold',
            fields=[
                ('innholdid', models.AutoField(db_column='InnholdID', primary_key=True, serialize=False)),
                ('navn', models.CharField(db_column='Navn', max_length=128)),
            ],
            options={
                'db_table': 'innhold',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pamelding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brukerid', models.IntegerField(db_column='BrukerID')),
                ('arrangementid', models.IntegerField(db_column='ArrangementID')),
                ('tidspunkt', models.DateTimeField(db_column='Tidspunkt')),
            ],
            options={
                'db_table': 'pamelding',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vertskap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brukerid', models.IntegerField(db_column='BrukerID')),
                ('arrangementid', models.IntegerField(db_column='ArrangementID')),
            ],
            options={
                'db_table': 'vertskap',
                'managed': False,
            },
        ),
    ]
